import { ReduxProvider } from '@/redux/provider'
import './globals.css'
import type { Metadata } from 'next'
import { Roboto_Mono } from 'next/font/google'
import { ThemeProvider } from '@/components/themeProvider/ThemProvider'

const RobotoMono = Roboto_Mono({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={RobotoMono.className}>
      <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <ReduxProvider>
            {children}
          </ReduxProvider>
      </ThemeProvider>
      </body>
    </html>
  )
}
