export const categoryMappings: {[key: string]: string } = {
  "Одежда": "Clothing",
  "Верхняя одежда": "Outerwear",
  "Платья и сарафаны": "DressesAndJumpsuits",
  "Футболки и топы": "TShirtsAndTops",
  "Брюки и джинсы": "PantsAndJeans",
  "Пиджаки и костюмы": "JacketsAndSuits",
  "Спортивная одежда": "Sportswear",
  "Одежда для пляжа": "Beachwear",
  "Нижнее бельё и пижамы": "UnderwearAndPajamas",
  "Свитеры и кофты": "SweatersAndCardigans",
  "Юбки и шорты": "SkirtsAndShorts",
  "Аксессуары": "Accessories",
  "Сумки и рюкзаки": "BagsAndBackpacks",
  "Шапки, шарфы, перчатки": "HatsScarvesGloves",
  "Очки и солнцезащитные очки": "GlassesAndSunglasses",
  "Ремни и пояса": "Belts",
  "Шляпы и береты": "HatsAndBerets",
  "Украшения": "Jewelry",
  "Кольца": "Rings",
  "Браслеты": "Bracelets",
  "Серьги": "Earrings",
  "Подвески и кулоны": "PendantsAndLockets",
  "Броши": "Brooches",
}

export const reverseCategoryMappings: {[key: string]: string } = {
  "Clothing": "Одежда",
  "Outerwear": "Верхняя одежда",
  "DressesAndJumpsuits": "Платья и сарафаны",
  "TShirtsAndTops": "Футболки и топы",
  "PantsAndJeans": "Брюки и джинсы",
  "JacketsAndSuits": "Пиджаки и костюмы",
  "Sportswear": "Спортивная одежда",
  "Beachwear": "Одежда для пляжа",
  "UnderwearAndPajamas": "Нижнее бельё и пижамы",
  "SweatersAndCardigans": "Свитеры и кофты",
  "SkirtsAndShorts": "Юбки и шорты",
  "Accessories": "Аксессуары",
  "BagsAndBackpacks": "Сумки и рюкзаки",
  "HatsScarvesGloves": "Шапки, шарфы, перчатки",
  "GlassesAndSunglasses": "Очки и солнцезащитные очки",
  "Belts": "Ремни и пояса",
  "HatsAndBerets": "Шляпы и береты",
  "Jewelry": "Украшения",
  "Rings": "Кольца",
  "Bracelets": "Браслеты",
  "Earrings": "Серьги",
  "PendantsAndLockets": "Подвески и кулоны",
  "Brooches": "Броши",
}